### ISSUE TITLE
Keeps jumping

### ISSUE THREAD

**Issue by devkhan** [xiangtailiang/FakeGPS#3]
Thanks or making this.

After a few minutes of use, sometimes it keeps jumping between tha real and the fake location.

Let me know if more info is required.

**Comment by xiangtailiang** [comment]
The real GPS maybe working and it output the real location and at the same time of the FakeGPS.
This problem will take a bit time to solved. For now , You can use indoors, so GPS signal is weak and the real GPS can not work.
 It is suggested that you choose "Locate by GPS" instead of "Locate by network and GPS".

**Comment by devkhan** [comment]
I do have the "Device only" mode of location set. Is there any way we can disable the actual GPS while the fake GPS thread is running?

**Comment by xiangtailiang** [comment]
Sorry , there is no idea disable the actual GPS if the ROM did not supported.

**Comment by devkhan** [comment]
Okay, thanks.
